package cmd

var stackMap = map[string]string{}
var categoryMap = map[string]string{}

func init() {
	categoryMap = map[string]string{
		"없음":                          "OTHER",
		"React.js":                    "FRONTEND",
		"Vue.js":                      "FRONTEND",
		"Next.js":                     "FRONTEND",
		"SvelteKit":                   "FRONTEND",
		"Angular":                     "FRONTEND",
		"Django":                      "BACKEND",
		"Flask":                       "BACKEND",
		"Ruby on Rails":               "BACKEND",
		"Spring Boot":                 "BACKEND",
		"Express.js":                  "BACKEND",
		"Laravel":                     "BACKEND",
		"S3/Cloud Storage":            "DEVOPS",
		"Go Lang":                     "BACKEND",
		"AI/ML (Tensorflow, PyTorch)": "OTHER",
		"Kubernetes":                  "DEVOPS",
		"Jenkins CI":                  "DEVOPS",
		"Github Actions":              "DEVOPS",
		"Spinnaker":                   "DEVOPS",
		"Graphite":                    "DEVOPS",
		"Kafka":                       "BACKEND",
		"Docker":                      "DEVOPS",
		"Ansible":                     "DEVOPS",
		"Terraform":                   "DEVOPS",
		"FastAPI":                     "BACKEND",
		"Redis":                       "DATABASE",
		"MSA":                         "BACKEND",
		"Java":                        "BACKEND",
		"Python":                      "BACKEND",
		"JavaScript/TypeScript":       "FRONTEND",
		"C/C++":                       "BACKEND",
		"C#":                          "BACKEND",
		"Ruby":                        "BACKEND",
		"AWS":                         "DEVOPS",
		"GCP":                         "DEVOPS",
		"ELK Stack":                   "DEVOPS",
		"Elasticsearch":               "DEVOPS",
		"Prometheus":                  "DEVOPS",
		"Grafana":                     "DEVOPS",
		"Celery":                      "BACKEND",
		"Nginx":                       "DEVOPS",
		"CDN (CloudFront)":            "DEVOPS",
		"Nest.JS":                     "BACKEND",
		"Zustand":                     "FRONTEND",
		"Tailwind CSS":                "FRONTEND",
		"Bootstrap":                   "FRONTEND",
		"PostgreSQL":                  "DATABASE",
		"MySQL":                       "DATABASE",
		"MongoDB":                     "DATABASE",
		"Node.js":                     "BACKEND",
		"Apollo GraphQL":              "BACKEND",
		"GraphQL":                     "BACKEND",
		"Redux":                       "FRONTEND",
		"MobX":                        "FRONTEND",
		"Vuex":                        "FRONTEND",
		"Jest":                        "FRONTEND",
		"Mocha":                       "FRONTEND",
		"Cypress":                     "FRONTEND",
		"Traefik":                     "DEVOPS",
		"Selenium":                    "OTHER",
		"gRPC":                        "OTHER",
		"Docker Compose":              "DEVOPS",
		"Docker Swarm":                "DEVOPS",
		"React Native":                "FRONTEND",
		"Flutter":                     "FRONTEND",
		"Figma":                       "OTHER",
		"Zeplin":                      "OTHER",
		"NX":                          "FRONTEND",
		"Shadcn/ui":                   "FRONTEND",
		"Turborepo":                   "FRONTEND",
		"Lerna":                       "FRONTEND",
		"Chromatic":                   "FRONTEND",
		"PlayWright":                  "FRONTEND",
		"Storybook":                   "FRONTEND",
		"Vite":                        "FRONTEND",
		"Vitest":                      "FRONTEND",
		"K6":                          "OTHER",
		"Locust":                      "OTHER",
		"JMeter":                      "OTHER",
		"Postman":                     "OTHER",
		"Insomnia":                    "OTHER",
		"React Testing Library":       "FRONTEND",
		"RabbitMQ":                    "DEVOPS",
		"Oracle Database":             "DATABASE",
		"Microsoft SQL Server":        "DATABASE",
		"MariaDB":                     "DATABASE",
		"SQLite":                      "DATABASE",
		"Firebase Firestore":          "DATABASE",
		"Couchbase":                   "DATABASE",
		"Neo4j":                       "DATABASE",
		"InfluxDB":                    "DATABASE",
		"Supabase":                    "DATABASE",
		"Amazon RDS":                  "DATABASE",
		"Goolge Cloud SQL":            "DATABASE",
		"Google BigQuery":             "DATABASE",
		"Memcached":                   "DATABASE",
		"Apache Flink":                "OTHER",
		"Airflow":                     "OTHER",
		"Debezium":                    "OTHER",
		"Gin":                         "BACKEND",
	}
	stackMap = map[string]string{
		"없음":                          ":none:",
		"React.js":                    ":react:",
		"Vue.js":                      ":vue:",
		"Next.js":                     ":next:",
		"SvelteKit":                   ":svelte:",
		"Angular":                     ":angular:",
		"Django":                      ":django:",
		"Flask":                       ":flask:",
		"Ruby on Rails":               ":rrails:",
		"Spring Boot":                 ":spring:",
		"Express.js":                  ":express:",
		"Laravel":                     ":laravel:",
		"S3/Cloud Storage":            ":s3:",
		"Go Lang":                     ":golang:",
		"AI/ML (Tensorflow, PyTorch)": ":ai:",
		"Kubernetes":                  ":kube:",
		"Jenkins CI":                  ":jenkins:",
		"Github Actions":              ":actions:",
		"Spinnaker":                   ":spin:",
		"Graphite":                    ":graphite:",
		"Kafka":                       ":kafka:",
		"Docker":                      ":docker:",
		"Ansible":                     ":ansible:",
		"Terraform":                   ":terraform:",
		"FastAPI":                     ":fast:",
		"Redis":                       ":redis:",
		"MSA":                         ":msa:",
		"Java":                        ":java:",
		"Python":                      ":python:",
		"JavaScript/TypeScript":       ":jsts:",
		"C/C++":                       ":cpp:",
		"C#":                          ":csh:",
		"Ruby":                        ":ruby:",
		"AWS":                         ":aws:",
		"GCP":                         ":gcp:",
		"ELK Stack":                   ":elk:",
		"Elasticsearch":               ":elasticsearch:",
		"Prometheus":                  ":prom:",
		"Grafana":                     ":grafana:",
		"Celery":                      ":celery:",
		"Nginx":                       ":nginx:",
		"CDN (CloudFront)":            ":cdn:",
		"Nest.JS":                     ":nest:",
		"Zustand":                     ":zustand:",
		"Tailwind CSS":                ":tailwind:",
		"Bootstrap":                   ":bootstrap:",
		"PostgreSQL":                  ":postgre:",
		"MySQL":                       ":mysql:",
		"MongoDB":                     ":mongo:",
		"Node.js":                     ":node:",
		"Apollo GraphQL":              ":apollo:",
		"GraphQL":                     ":graphql:",
		"Redux":                       ":redux:",
		"MobX":                        ":mobx:",
		"Vuex":                        ":vuex:",
		"Jest":                        ":jest:",
		"Mocha":                       ":mocha:",
		"Cypress":                     ":cypress:",
		"Traefik":                     ":traefik:",
		"Selenium":                    ":selenium:",
		"gRPC":                        ":grpc:",
		"Docker Compose":              ":compose:",
		"Docker Swarm":                ":swarm:",
		"React Native":                ":rn:",
		"Flutter":                     ":flutter:",
		"Figma":                       ":figma:",
		"Zeplin":                      ":zeplin:",
		"NX":                          ":nx:",
		"Shadcn/ui":                   ":shad:",
		"Turborepo":                   ":turbo:",
		"Lerna":                       ":lerna:",
		"Chromatic":                   ":chromatic:",
		"PlayWright":                  ":playwright:",
		"Storybook":                   ":story:",
		"Vite":                        ":vite:",
		"Vitest":                      ":vitest:",
		"K6":                          ":k6:",
		"Locust":                      ":locust:",
		"JMeter":                      ":jmeter:",
		"Postman":                     ":postman:",
		"Insomnia":                    ":insomnia:",
		"React Testing Library":       ":rtl:",
		"RabbitMQ":                    ":rabbitmq:",
		"Oracle Database":             ":oracle:",
		"Microsoft SQL Server":        ":microsql:",
		"MariaDB":                     ":mariadb:",
		"SQLite":                      ":sqlite:",
		"Firebase Firestore":          ":firebase:",
		"Couchbase":                   ":couchbase:",
		"Neo4j":                       ":neo4j:",
		"InfluxDB":                    ":influxdb:",
		"Supabase":                    ":supabase:",
		"Amazon RDS":                  ":rds:",
		"Goolge Cloud SQL":            ":cloudsql:",
		"Google BigQuery":             ":bigquery:",
		"Memcached":                   ":memcached:",
		"Apache Flink":                ":flink:",
		"Airflow":                     ":airflow:",
		"Debezium":                    ":debezium:",
		"Gin":                         ":gin:",
	}
}
