// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alert/channel": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Send channel message to find_member channel (legacy)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert"
                ],
                "summary": "Send channel message to find_member channel (legacy)",
                "parameters": [
                    {
                        "description": "FindMemberSchema",
                        "name": "models.FindMemberSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FindMemberSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Channel message sent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/alert/find-member": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Send Message to Find member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert"
                ],
                "summary": "Send Message to Find member",
                "parameters": [
                    {
                        "description": "FindMemberSchema",
                        "name": "models.FindMemberSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FindMemberSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/alert/message": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Send alert message. Type은 \"user\" 또는 \"channel\" 중 하나",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert"
                ],
                "summary": "Send alert message",
                "parameters": [
                    {
                        "description": "AlertMessageSchema",
                        "name": "models.AlertMessageSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AlertMessageSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert message sent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/alert/user": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Send user message (legacy)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert"
                ],
                "summary": "Send user message (legacy)",
                "parameters": [
                    {
                        "description": "UserMessageSchema",
                        "name": "models.UserMessageSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserMessageSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User message sent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deploy/image": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Deploy image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploy"
                ],
                "summary": "Deploy image",
                "parameters": [
                    {
                        "description": "Deployment request",
                        "name": "deployRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ImageDeployRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment request received",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deploy/status": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Deploy status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploy"
                ],
                "summary": "Deploy status",
                "parameters": [
                    {
                        "description": "Status request",
                        "name": "statusRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status request received",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/picture": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get profile picture",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profile picture",
                "parameters": [
                    {
                        "description": "Profile picture request",
                        "name": "profilePictureRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProfilePictureRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile picture retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ProfilePictureResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/slack/interactions": {
            "post": {
                "security": [
                    {
                        "SlackSigningSecret": []
                    }
                ],
                "description": "Handle Slack interaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Handle Slack interaction",
                "responses": {
                    "200": {
                        "description": "Slack interaction received",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AlertMessageSchema": {
            "type": "object",
            "properties": {
                "channelId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.FindMemberSchema": {
            "type": "object",
            "properties": {
                "backNum": {
                    "type": "integer"
                },
                "dataEngNum": {
                    "type": "integer"
                },
                "devOpsNum": {
                    "type": "integer"
                },
                "email": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "frontNum": {
                    "type": "integer"
                },
                "fullStack": {
                    "type": "integer"
                },
                "goal": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "leader": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "notionLink": {
                    "type": "string"
                },
                "projectExplain": {
                    "type": "string"
                },
                "recruitExplain": {
                    "type": "string"
                },
                "recruitNum": {
                    "type": "integer"
                },
                "rule": {
                    "type": "string"
                },
                "stack": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "studyExplain": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ImageDeployRequest": {
            "type": "object",
            "properties": {
                "commitLink": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "imageName": {
                    "type": "string"
                },
                "imageTag": {
                    "type": "string"
                }
            }
        },
        "models.ProfilePictureRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "models.ProfilePictureResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "isTecheer": {
                    "type": "boolean"
                }
            }
        },
        "models.StatusRequest": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "failedStep": {
                    "type": "string"
                },
                "imageName": {
                    "type": "string"
                },
                "imageTag": {
                    "type": "string"
                },
                "jobURL": {
                    "type": "string"
                },
                "logs": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.UserMessageSchema": {
            "type": "object",
            "properties": {
                "applicantEmail": {
                    "type": "string"
                },
                "leaderEmail": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "teamId": {
                    "type": "integer"
                },
                "teamName": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "JwtAuth": {
            "type": "apiKey",
            "name": "access_token",
            "in": "cookie"
        },
        "SlackSigningSecret": {
            "type": "apiKey",
            "name": "X-Slack-Signature",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
